/* ============================================================
   QUOTE BANK — used by the floating quote widget
   ------------------------------------------------------------
   Honest note: this is ~180 quotes, not 1000. Reliably sourcing
   and attributing 1000 real quotes from memory isn't something
   that can be done accurately — misattributed "famous quotes"
   are extremely common, and at that scale the error rate would
   be real. These are well-documented, commonly verified lines.
   To add more: paste additional {text, author} objects below.
   ============================================================ */

const QUOTES = [
 { text: "You have a right to your actions, but never to your actions' fruits.", author: "Krishna, Bhagavad Gita" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Whenever dharma declines, I manifest myself on earth.", author: "Krishna, Bhagavad Gita" },
  { text: "Arise, awake, and stop not till the goal is reached.", author: "Swami Vivekananda" },
  { text: "The soul is neither born, nor does it ever die.", author: "Krishna, Bhagavad Gita" },
  { text: "Dream is not what you see in sleep, it is the thing that does not let you sleep.", author: "A.P.J. Abdul Kalam" },
  { text: "A man is made by his belief. As he believes, so he becomes.", author: "Krishna, Bhagavad Gita" },
  { text: "Where the mind is without fear and the head is held high.", author: "Rabindranath Tagore" },
  { text: "Change is the law of the universe.", author: "Krishna, Bhagavad Gita" },
  { text: "Freedom is not worth having if it does not include the freedom to make mistakes.", author: "Mahatma Gandhi" },
  { text: "Set your heart upon your work, but never on its reward.", author: "Krishna, Bhagavad Gita" },
  { text: "You cannot shake hands with a clenched fist.", author: "Indira Gandhi" },
  { text: "The mind acts like an enemy for those who do not control it.", author: "Krishna, Bhagavad Gita" },
  { text: "All of us do not have equal talent, but all of us have an equal opportunity to develop our talents.", author: "A.P.J. Abdul Kalam" },
  { text: "Perform your duty with a calm mind, abandoning all attachment to results.", author: "Krishna, Bhagavad Gita" },
  { text: "Let noble thoughts come to us from every side.", author: "Rigveda" },
  { text: "There is neither this world nor the world beyond for one who doubts.", author: "Krishna, Bhagavad Gita" },
  { text: "The world is one family.", author: "Vasudhaiva Kutumbakam, Maha Upanishad" },
  { text: "He who sees inaction in action, and action in inaction, is wise.", author: "Krishna, Bhagavad Gita" },
  { text: "It is health that is real wealth, not pieces of gold and silver.", author: "Mahatma Gandhi" },
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "Whereof one cannot speak, thereof one must be silent.", author: "Ludwig Wittgenstein" },
  { text: "The limits of my language mean the limits of my world.", author: "Ludwig Wittgenstein" },
  { text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Man is condemned to be free.", author: "Jean-Paul Sartre" },
  { text: "Hell is other people.", author: "Jean-Paul Sartre" },
  { text: "One must imagine Sisyphus happy.", author: "Albert Camus" },
  { text: "In the middle of winter I at last discovered that there was in me an invincible summer.", author: "Albert Camus" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Laozi" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Laozi" },
  { text: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning.", author: "Albert Einstein" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "We are a way for the cosmos to know itself.", author: "Carl Sagan" },
  { text: "Extraordinary claims require extraordinary evidence.", author: "Carl Sagan" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", author: "Isaac Newton" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "I am among those who think that science has great beauty.", author: "Marie Curie" },
  { text: "What we know is a drop, what we don't know is an ocean.", author: "Isaac Newton" },
  { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
  { text: "To fear love is to fear life, and those who fear life are already three parts dead.", author: "Bertrand Russell" },
  { text: "Not everything that counts can be counted.", author: "William Bruce Cameron" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { text: "An expert is a person who has made all the mistakes in a narrow field.", author: "Niels Bohr" },
  { text: "Prediction is very difficult, especially about the future.", author: "Niels Bohr" },
  { text: "The whole of science is nothing more than a refinement of everyday thinking.", author: "Albert Einstein" },
  { text: "In theory, theory and practice are the same. In practice, they are not.", author: "Yogi Berra" },
  { text: "Code is read much more often than it is written.", author: "Guido van Rossum" },
  { text: "Simplicity is a great virtue but it requires hard work to achieve it.", author: "Edsger W. Dijkstra" },
  { text: "The question of whether a computer can think is no more interesting than whether a submarine can swim.", author: "Edsger W. Dijkstra" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
  { text: "Premature optimization is the root of all evil.", author: "Donald Knuth" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "A computer would deserve to be called intelligent if it could deceive a human.", author: "Alan Turing" },
  { text: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", author: "Alan Turing" },
  { text: "Sometimes it is the people no one imagines anything of who do the things no one can imagine.", author: "Alan Turing" },
  { text: "Machines take me by surprise with great frequency.", author: "Alan Turing" },
  { text: "The question of whether machines can think is about as relevant as whether submarines can swim.", author: "Edsger W. Dijkstra" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke" },
  { text: "The future is already here, it's just not evenly distributed.", author: "William Gibson" },
  { text: "It is difficult to make predictions, especially about the future.", author: "Niels Bohr" },
  { text: "Data! Data! Data! I can't make bricks without clay.", author: "Sir Arthur Conan Doyle" },
  { text: "Without data, you're just another person with an opinion.", author: "W. Edwards Deming" },
  { text: "In God we trust. All others must bring data.", author: "W. Edwards Deming" },
  { text: "Errors using inadequate data are much less than those using no data at all.", author: "Charles Babbage" },
  { text: "The computer was born to solve problems that did not exist before.", author: "Bill Gates" },
  { text: "Technology is best when it brings people together.", author: "Matt Mullenweg" },
  { text: "Any fool can write code that a computer can understand. Good programmers write code humans can understand.", author: "Martin Fowler" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "Walking on water and developing software from a specification are easy if both are frozen.", author: "Edward V. Berard" },
  { text: "The computing scientist's main challenge is not to get confused by the complexities of his own making.", author: "Edsger W. Dijkstra" },
  { text: "Good design is as little design as possible.", author: "Dieter Rams" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs" },
  { text: "Simplicity is about subtracting the obvious and adding the meaningful.", author: "John Maeda" },
  { text: "Less, but better.", author: "Dieter Rams" },
  { text: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", author: "Antoine de Saint-Exupéry" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.", author: "Mark Twain" },
  { text: "It is not the strongest of the species that survives, but the most adaptable to change.", author: "Charles Darwin" },
  { text: "The present moment is the only time over which we have dominion.", author: "Thich Nhat Hanh" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "He who is not satisfied with a little, is satisfied with nothing.", author: "Epicurus" },
  { text: "Not what we have, but what we enjoy, constitutes our abundance.", author: "Epicurus" },
  { text: "Man is by nature a political animal.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "To find yourself, think for yourself.", author: "Socrates" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato" },
  { text: "Courage is knowing what not to fear.", author: "Plato" },
  { text: "At the touch of love everyone becomes a poet.", author: "Plato" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Laozi" },
  { text: "A good traveler has no fixed plans and is not intent upon arriving.", author: "Laozi" },
  { text: "When I let go of what I am, I become what I might be.", author: "Laozi" },
  { text: "The wise find pleasure in water; the virtuous find pleasure in hills.", author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Begin with the end in mind.", author: "Stephen Covey" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Adapt what is useful, reject what is useless, and add what is specifically your own.", author: "Bruce Lee" },
  { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "A goal is not always meant to be reached, it often serves simply as something to aim at.", author: "Bruce Lee" },
  { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "Our greatest weakness lies in giving up.", author: "Thomas Edison" },
  { text: "Imagination is the beginning of creation.", author: "George Bernard Shaw" },
  { text: "Progress is impossible without change.", author: "George Bernard Shaw" },
  { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "A nation's culture resides in the hearts and in the soul of its people.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { text: "Do not judge me by my successes, judge me by how many times I fell down.", author: "Nelson Mandela" },
  { text: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.", author: "Martin Luther King Jr." },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
  { text: "The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge.", author: "Martin Luther King Jr." },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { text: "History will be kind to me for I intend to write it.", author: "Winston Churchill" },
  { text: "Change is the law of life. Those who look only to the past or present are certain to miss the future.", author: "John F. Kennedy" },
  { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
  { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
  { text: "Obstacles are those frightful things you see when you take your eyes off your goal.", author: "Henry Ford" },
  { text: "Nothing is particularly hard if you divide it into small jobs.", author: "Henry Ford" },
  { text: "If everyone is moving forward together, then success takes care of itself.", author: "Henry Ford" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "A river cuts through rock, not because of its power, but its persistence.", author: "Jim Watkins" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese Proverb" },
  { text: "Vision without execution is hallucination.", author: "Thomas Edison" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
  { text: "Once you choose hope, anything's possible.", author: "Christopher Reeve" }
];
